// All data paths and app-wide constants live here.
// In development: Vite serves files from /public/data/.
// In production (Vercel): same paths resolve from the built static bundle.
// To add data: copy your outputs/ files into dashboard/public/data/.

export const DATA_BASE = '/data'

export const DATA_FILES = {
  policy_summary    : `${DATA_BASE}/policy_summary.csv`,
  district_tiers    : `${DATA_BASE}/district_tiers.csv`,
  shap_values       : `${DATA_BASE}/shap_values.csv`,
  flood_contingency : `${DATA_BASE}/flood_contingency.csv`,
  drought_contingency: `${DATA_BASE}/drought_contingency.csv`,
  model_metrics     : `${DATA_BASE}/model_comparison_metrics.csv`,
  merged_annual     : `${DATA_BASE}/merged_annual.csv`,
  casa_predictions  : `${DATA_BASE}/casa_net_predictions.csv`,
  geojson           : `${DATA_BASE}/enriched_districts.geojson`,

  // SHAP plot images generated by Script 7
  shap_beeswarm     : `${DATA_BASE}/shap_summary_beeswarm.png`,
  gate_weights_chart: `${DATA_BASE}/gate_weights_chart.png`,
  shap_validation   : `${DATA_BASE}/shap_vs_attribution_validation.png`,
}

// Districts with individual waterfall charts from Script 7
export const WATERFALL_DISTRICTS = [
  'Coimbatore', 'Namakkal', 'Tiruppur', 'Theni', 'Krishnagiri'
]

export const TIER_COLORS = {
  1: '#c0392b',
  2: '#e67e22',
  3: '#f1c40f',
  4: '#27ae60',
}

export const TIER_LABELS = {
  1: 'Act Now',
  2: 'Plan Now',
  3: 'Monitor',
  4: 'Stable',
}

export const DEPTH_COLOR_SCALE = [
  { threshold: 3,   color: '#27ae60' },
  { threshold: 5,   color: '#f1c40f' },
  { threshold: 8,   color: '#e67e22' },
  { threshold: 999, color: '#c0392b' },
]

export const RISK_COLORS = {
  HIGH  : '#c0392b',
  MEDIUM: '#e67e22',
  LOW   : '#27ae60',
}
